### ISSUE TITLE
Remove eslint rule ignore

### ISSUE THREAD

**Issue by Arthurmtro** [nelak2/nwscript-sinfar-language-server#4]
This is a bad practice to make uses of this

https://github.com/nelak2/nwscript-sinfar-language-server/blob/c5afa5430fef7296ccdbac865df96269efc1e7b9/client/src/extension.ts#L167-L168

**Comment by nelak2** [comment]
In that case specifically removing the ` // eslint-disable-next-line @typescript-eslint/no-unused-vars` causes it to flag the `session` variable because it is not used.

However, the way `getSession()` works is that if a valid session is not found, it creates a new session and triggers the login procedure. So while I don't use `session` it is still important to call `getSession()` at that point.

Just to confirm my understanding of how await works in Typescript then:

This will call the async function and it simply continues execution without waiting for the async function to complete:
`void vscode.authentication.getSession(CookieAuthenticationProvider.id, [], { createIfNone: true });`
This will call the async function but it will wait until the async function has resolved before proceeding to the next line:
`await vscode.authentication.getSession(CookieAuthenticationProvider.id, [], { createIfNone: true });`

To resolve this issue, I would want to remove the `const session = `.

**Comment by Arthurmtro** [comment]
Yes exactly you have to remove the `const session = `
